spring.datasource.url=jdbc:mysql://localhost:3306/manutencao_equipamentos?useSSL=false&serverTimezone=America/Sao_Paulo
# ---------------------------------------------
# ALTERAR PARA AS SUAS CREDENCIAIS!
spring.datasource.username=root
spring.datasource.password=ywmbBny4mn//
# ---------------------------------------------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.application.name=backend
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=repairio.assist@gmail.com
spring.mail.password=ggxi zxhm sazj vzxz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Garante que o Jackson (serialização JSON) use o timezone correto
spring.jackson.time-zone=America/Sao_Paulo
